name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "876c2779-d3cc-4f0e-bd43-617b902f0a11"
database_name = "memos-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "170e9ae4fc4b4cfa8b18a399665e65c8"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "memos-r2-bucket"
preview_bucket_name = "notes-files-preview"
